# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1073, 559)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 10, 640, 480))
        self.label.setText("")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(700, 10, 331, 531))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 61, 16))
        self.label_3.setObjectName("label_3")
        self.portname = QtWidgets.QComboBox(self.groupBox_3)
        self.portname.setGeometry(QtCore.QRect(80, 30, 131, 21))
        self.portname.setEditable(False)
        self.portname.setObjectName("portname")
        self.baudrate = QtWidgets.QComboBox(self.groupBox_3)
        self.baudrate.setGeometry(QtCore.QRect(80, 90, 131, 21))
        self.baudrate.setObjectName("baudrate")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.setItemText(6, "")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 61, 16))
        self.label_2.setObjectName("label_2")
        self.UartBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.UartBtn.setGeometry(QtCore.QRect(100, 140, 75, 23))
        self.UartBtn.setObjectName("UartBtn")
        self.Refresh = QtWidgets.QPushButton(self.groupBox_3)
        self.Refresh.setGeometry(QtCore.QRect(10, 140, 75, 23))
        self.Refresh.setObjectName("Refresh")
        self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Reset = QtWidgets.QPushButton(self.groupBox_2)
        self.Reset.setObjectName("Reset")
        self.gridLayout_2.addWidget(self.Reset, 0, 2, 1, 1)
        self.Exit = QtWidgets.QPushButton(self.groupBox_2)
        self.Exit.setObjectName("Exit")
        self.gridLayout_2.addWidget(self.Exit, 0, 3, 1, 1)
        self.Pause = QtWidgets.QPushButton(self.groupBox_2)
        self.Pause.setObjectName("Pause")
        self.gridLayout_2.addWidget(self.Pause, 0, 1, 1, 1)
        self.Start = QtWidgets.QPushButton(self.groupBox_2)
        self.Start.setObjectName("Start")
        self.gridLayout_2.addWidget(self.Start, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.display_angle = QtWidgets.QLabel(self.groupBox)
        self.display_angle.setGeometry(QtCore.QRect(108, 74, 47, 16))
        self.display_angle.setText("")
        self.display_angle.setObjectName("display_angle")
        self.display_distance = QtWidgets.QLabel(self.groupBox)
        self.display_distance.setGeometry(QtCore.QRect(108, 23, 47, 16))
        self.display_distance.setText("")
        self.display_distance.setObjectName("display_distance")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 74, 31, 16))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 23, 45, 16))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_3.setTitle(_translate("Form", "USART"))
        self.label_3.setText(_translate("Form", "Baud Rate"))
        self.baudrate.setCurrentText(_translate("Form", "1200"))
        self.baudrate.setItemText(0, _translate("Form", "1200"))
        self.baudrate.setItemText(1, _translate("Form", "2400"))
        self.baudrate.setItemText(2, _translate("Form", "4800"))
        self.baudrate.setItemText(3, _translate("Form", "9600"))
        self.baudrate.setItemText(4, _translate("Form", "19200"))
        self.baudrate.setItemText(5, _translate("Form", "115200"))
        self.label_2.setText(_translate("Form", "Port Name"))
        self.UartBtn.setText(_translate("Form", "Connect"))
        self.Refresh.setText(_translate("Form", "Refresh"))
        self.groupBox_2.setTitle(_translate("Form", "Control"))
        self.Reset.setText(_translate("Form", "Reset"))
        self.Exit.setText(_translate("Form", "Exit"))
        self.Pause.setText(_translate("Form", "Pause"))
        self.Start.setText(_translate("Form", "Start"))
        self.groupBox.setTitle(_translate("Form", "Object"))
        self.label_5.setText(_translate("Form", "Angle:"))
        self.label_4.setText(_translate("Form", "Distance:"))





