# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1069, 604)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 10, 651, 581))
        self.label.setText("")
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(700, 380, 359, 211))
        self.groupBox.setObjectName("groupBox")
        self.display_angle = QtWidgets.QLabel(self.groupBox)
        self.display_angle.setGeometry(QtCore.QRect(108, 74, 47, 16))
        self.display_angle.setText("")
        self.display_angle.setObjectName("display_angle")
        self.display_distance = QtWidgets.QLabel(self.groupBox)
        self.display_distance.setGeometry(QtCore.QRect(108, 23, 47, 16))
        self.display_distance.setText("")
        self.display_distance.setObjectName("display_distance")
        self.sent_box = QtWidgets.QTextEdit(self.groupBox)
        self.sent_box.setGeometry(QtCore.QRect(10, 20, 341, 181))
        self.sent_box.setObjectName("sent_box")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(700, 140, 359, 241))
        self.groupBox_2.setObjectName("groupBox_2")
        self.Start = QtWidgets.QPushButton(self.groupBox_2)
        self.Start.setGeometry(QtCore.QRect(10, 30, 75, 23))
        self.Start.setObjectName("Start")
        self.Pause = QtWidgets.QPushButton(self.groupBox_2)
        self.Pause.setGeometry(QtCore.QRect(90, 30, 75, 23))
        self.Pause.setObjectName("Pause")
        self.Reset = QtWidgets.QPushButton(self.groupBox_2)
        self.Reset.setGeometry(QtCore.QRect(170, 30, 75, 23))
        self.Reset.setObjectName("Reset")
        self.Exit = QtWidgets.QPushButton(self.groupBox_2)
        self.Exit.setGeometry(QtCore.QRect(250, 30, 75, 23))
        self.Exit.setObjectName("Exit")
        self.show_keypoints = QtWidgets.QCheckBox(self.groupBox_2)
        self.show_keypoints.setGeometry(QtCore.QRect(10, 80, 151, 17))
        self.show_keypoints.setObjectName("show_keypoints")
        self.show_bounding_rectangle = QtWidgets.QCheckBox(self.groupBox_2)
        self.show_bounding_rectangle.setGeometry(QtCore.QRect(200, 80, 151, 17))
        self.show_bounding_rectangle.setObjectName("show_bounding_rectangle")
        self.keypoints_accuracy_slider = QtWidgets.QSlider(self.groupBox_2)
        self.keypoints_accuracy_slider.setGeometry(QtCore.QRect(180, 120, 160, 22))
        self.keypoints_accuracy_slider.setMaximum(100)
        self.keypoints_accuracy_slider.setProperty("value", 50)
        self.keypoints_accuracy_slider.setSliderPosition(50)
        self.keypoints_accuracy_slider.setOrientation(QtCore.Qt.Horizontal)
        self.keypoints_accuracy_slider.setObjectName("keypoints_accuracy_slider")
        self.rectangle_accuracy_slider = QtWidgets.QSlider(self.groupBox_2)
        self.rectangle_accuracy_slider.setGeometry(QtCore.QRect(180, 160, 160, 22))
        self.rectangle_accuracy_slider.setMaximum(100)
        self.rectangle_accuracy_slider.setSliderPosition(90)
        self.rectangle_accuracy_slider.setOrientation(QtCore.Qt.Horizontal)
        self.rectangle_accuracy_slider.setObjectName("rectangle_accuracy_slider")
        self.object_accuracy_slider = QtWidgets.QSlider(self.groupBox_2)
        self.object_accuracy_slider.setGeometry(QtCore.QRect(180, 200, 160, 22))
        self.object_accuracy_slider.setMaximum(100)
        self.object_accuracy_slider.setSingleStep(1)
        self.object_accuracy_slider.setSliderPosition(80)
        self.object_accuracy_slider.setOrientation(QtCore.Qt.Horizontal)
        self.object_accuracy_slider.setObjectName("object_accuracy_slider")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 141, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 200, 141, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 120, 141, 16))
        self.label_8.setObjectName("label_8")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(700, 11, 359, 131))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 61, 16))
        self.label_3.setObjectName("label_3")
        self.portname = QtWidgets.QComboBox(self.groupBox_3)
        self.portname.setGeometry(QtCore.QRect(80, 30, 131, 21))
        self.portname.setEditable(False)
        self.portname.setObjectName("portname")
        self.baudrate = QtWidgets.QComboBox(self.groupBox_3)
        self.baudrate.setGeometry(QtCore.QRect(80, 90, 131, 21))
        self.baudrate.setObjectName("baudrate")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 61, 16))
        self.label_2.setObjectName("label_2")
        self.UartBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.UartBtn.setGeometry(QtCore.QRect(260, 90, 75, 23))
        self.UartBtn.setObjectName("UartBtn")
        self.Refresh = QtWidgets.QPushButton(self.groupBox_3)
        self.Refresh.setGeometry(QtCore.QRect(260, 30, 75, 23))
        self.Refresh.setObjectName("Refresh")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Object"))
        self.groupBox_2.setTitle(_translate("Form", "Control"))
        self.Start.setText(_translate("Form", "Start"))
        self.Pause.setText(_translate("Form", "Pause"))
        self.Reset.setText(_translate("Form", "Reset"))
        self.Exit.setText(_translate("Form", "Exit"))
        self.show_keypoints.setText(_translate("Form", "Show keypoints"))
        self.show_bounding_rectangle.setText(_translate("Form", "Show bounding rectangle"))
        self.label_6.setText(_translate("Form", "Rectangle Accuracy:"))
        self.label_7.setText(_translate("Form", "Object Accuracy:"))
        self.label_8.setText(_translate("Form", "Keypoints Accuracy:"))
        self.groupBox_3.setTitle(_translate("Form", "USART"))
        self.label_3.setText(_translate("Form", "Baud Rate"))
        
        self.baudrate.setItemText(0, _translate("Form", "1200"))
        self.baudrate.setItemText(1, _translate("Form", "2400"))
        self.baudrate.setItemText(2, _translate("Form", "4800"))
        self.baudrate.setItemText(3, _translate("Form", "9600"))
        self.baudrate.setItemText(4, _translate("Form", "19200"))
        self.baudrate.setItemText(5, _translate("Form", "115200"))

        self.baudrate.setCurrentText(_translate("Form", "115200"))
        
        self.label_2.setText(_translate("Form", "Port Name"))
        self.UartBtn.setText(_translate("Form", "Connect"))
        self.Refresh.setText(_translate("Form", "Refresh"))

